apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-cluster-admin-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
