apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod

  initContainers:
    - name: init-web
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app

  containers: # Описание контейнеров внутри Pod
    - name: web
      image: vurazov/kubernetes-intro:v4 # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: /app

  volumes:
    - name: app
      emptyDir: { }